controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints: [motor_joint, indicator_joint]
      gains:
        motor_joint: {p: 1.0, i: 0.1, d: 0.01}
