<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- 
    Macro that defines the geometry and kinematics of the Quanser Qube.
    Includes:
    - A black base cube
    - A red spinning disk mounted on top
    - A white indicator fixed to the disk
    - A continuous joint (motor_joint) and a fixed joint (indicator_joint)
  -->

  <xacro:macro name="qube">
  <!-- Parameters -->
    <xacro:property name="box_size" value="0.1" />  <!-- Size of the black base cube (10 cm) -->
    <xacro:property name="disk_radius" value="0.025" />  <!-- Radius of the red spinning disk (2.5 cm) -->
    <xacro:property name="disk_height" value="0.01" />  <!-- Thickness of the disk (1 cm) -->
    <xacro:property name="indicator_length" value="0.025" />  <!-- Length of the indicator (2.5 cm) -->
    <xacro:property name="indicator_width" value="0.002" />  <!-- Width of the indicator strip -->
    <xacro:property name="indicator_height" value="0.001" />  <!-- Thickness of the indicator -->
    
    <!-- Cube -->
    <link name="base_link">
      <visual>
        <geometry><box size="${box_size} ${box_size} ${box_size}"/></geometry>
        <material name="black"><color rgba="0 0 0 1"/></material>
      </visual>
    </link>

    <!-- Spinning disk -->
    <link name="spinning_disk">
      <visual name="disk">
        <geometry>
          <cylinder radius="${disk_radius}" length="${disk_height}"/>
        </geometry>
        <material name="red">
          <color rgba="1 0 0 1"/>
        </material>
      </visual>
    </link>

    <!-- Indicator -->
    <link name="disk_indicator">
      <visual>
        <geometry>
          <box size="${indicator_length} ${indicator_width} ${indicator_height}"/>
        </geometry>
        <material name="white">
          <color rgba="1 1 1 1"/>
        </material>
      </visual>
    </link>


    <!-- Motor joint, Connects base to spinning disk.
         Rotates around Z-axis (0 0 -1). -->

    <joint name="motor_joint" type="continuous">
      <parent link="base_link"/>
      <child link="spinning_disk"/>
      <origin xyz="0 0 ${box_size/2 + disk_height/2}" rpy="0 0 0"/>
      <axis xyz="0 0 -1"/>
    </joint>

    <!-- Disk joint, fixed joint attaching white indicator to the red disk.-->
    <joint name="indicator_joint" type="fixed">
      <parent link="spinning_disk"/>
      <child link="disk_indicator"/>
      <origin xyz="${disk_radius - indicator_length/2} 0 ${disk_height/2 + indicator_height/2}" rpy="0 0 0"/>
    </joint>

  </xacro:macro>
</robot>
